repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint:fix
        language: system
        files: "^packages/.*/src/.*/?.*.(js|jsx|ts|tsx)$"
        types: [file]
