repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npm run prettier --write
        language: system
        files: "^packages/.*/src/.*/?.*.(js|jsx|ts|tsx)$"
        types: [file]
      - id: eslint
        name: eslint
        entry: npm run eslint --fix
        language: system
        files: "^packages/.*/src/.*/?.*.(js|jsx|ts|tsx)$"
        types: [file]
      - id: stylelint
        name: stylelint
        entry: npm run stylelint --fix
        language: system
        files: "^packages/.*/src/.*/?.*.(css|scss|less)$"
        types: [file]
