ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/regebro/pyroma
    rev: "4.2"
    hooks:
      - id: pyroma
